### ISSUE TITLE
VP9: "Media encoding is pending"

### ISSUE THREAD

**Issue by DecaTec** [mediacms-io/mediacms#435]
**Describe the issue**
By default, only H264 encoding profiles are active. As I wanted to try VP9 in terms of encoding speed and file size, I've deactivated all H264 encoding profiles and activated all for VP9.

Now, even if an uploaded video was transcoded sucessfully, I cannot play this video. Only the message "Media encoding is pending" is shown.

**To Reproduce**
Steps to reproduce the issue:
1. In the admin interface, disbale all H264 encoding profiles and active all VP9 encoding profiles.
2. Upload new video and wait for it to be transcoded.
3. Try to play the video. Here only "Media encoding is pending" is shown.
4. In the admin UI, check the available encodings for this video: All have a percentage of '100' and state 'Success'

**Expected behavior**
Videos transcoded should play as H264 transcoded videos.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Installation method: single server install
 - Browser: Chrome/Firefox

**Logs**

A `tail -f logs/*` gives following output:
```
==> logs/beatcelery_beat.log <==
[2022-03-30 12:39:49,084: INFO/MainProcess] beat: Starting...
[2022-03-30 14:09:02,474: INFO/MainProcess] beat: Starting...
[2022-03-30 21:01:00,072: INFO/MainProcess] Scheduler: Sending due task get_list_of_popular_media (get_list_of_popular_media)
[2022-03-31 01:01:00,008: INFO/MainProcess] Scheduler: Sending due task get_list_of_popular_media (get_list_of_popular_media)
[2022-03-31 01:02:00,001: INFO/MainProcess] Scheduler: Sending due task update_listings_thumbnails (update_listings_thumbnails)

==> logs/celery_long.log <==
    R = retval = fun(*args, **kwargs)
  File "/home/mediacms.io/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/mediacms.io/mediacms/files/tasks.py", line 352, in encode_media
    ret = media_file_info(tf)
  File "/home/mediacms.io/mediacms/files/helpers.py", line 446, in media_file_info
    stream_size = sum([int(line) for line in stdout.split("\n") if line != ""])
  File "/home/mediacms.io/mediacms/files/helpers.py", line 446, in <listcomp>
    stream_size = sum([int(line) for line in stdout.split("\n") if line != ""])
ValueError: invalid literal for int() with base 10: '311|'

==> logs/celery_short.log <==
[2022-03-31 10:40:20,432: INFO/MainProcess] Received task: save_user_action[48f1c72d-f134-4cf5-b1fc-e0e6971f333f]  
[2022-03-31 10:40:20,488: INFO/ForkPoolWorker-7] Task save_user_action[48f1c72d-f134-4cf5-b1fc-e0e6971f333f] succeeded in 0.0547746800002642s: True
[2022-03-31 10:45:36,830: INFO/MainProcess] Received task: save_user_action[294ee626-e66f-4b94-83af-8addebc72ca5]  
[2022-03-31 10:45:36,895: INFO/ForkPoolWorker-7] Task save_user_action[294ee626-e66f-4b94-83af-8addebc72ca5] succeeded in 0.061443854006938636s: True
[2022-03-31 10:46:00,306: INFO/MainProcess] Received task: save_user_action[0dbbf090-2c65-4e97-a341-303419cf7140]  
[2022-03-31 10:46:00,338: INFO/ForkPoolWorker-7] Task save_user_action[0dbbf090-2c65-4e97-a341-303419cf7140] succeeded in 0.029936609003925696s: False
[2022-03-31 10:47:25,946: INFO/MainProcess] Received task: save_user_action[d621aed9-f41b-446b-b4ed-3f3f2c7e5dc5]  
[2022-03-31 10:47:25,998: INFO/ForkPoolWorker-7] Task save_user_action[d621aed9-f41b-446b-b4ed-3f3f2c7e5dc5] succeeded in 0.05101300499518402s: True
[2022-03-31 10:47:32,180: INFO/MainProcess] Received task: save_user_action[c5827fa3-9287-4aa8-a441-a5f83c57a918]  
[2022-03-31 10:47:32,235: INFO/ForkPoolWorker-7] Task save_user_action[c5827fa3-9287-4aa8-a441-a5f83c57a918] succeeded in 0.05409067700384185s: True

==> logs/debug.log <==

==> logs/errorlog.txt <==
/home/mediacms.io/lib/python3.8/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'files.models.Playlist'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
/home/mediacms.io/lib/python3.8/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'files.models.Playlist'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
/home/mediacms.io/lib/python3.8/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'files.models.Playlist'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
/home/mediacms.io/lib/python3.8/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'files.models.Playlist'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
/home/mediacms.io/lib/python3.8/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'files.models.Playlist'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)

==> logs/celery_short.log <==
[2022-03-31 10:48:25,296: INFO/MainProcess] Received task: save_user_action[882a4253-15c0-44e6-96cd-640ca5b7526f]  
[2022-03-31 10:48:25,350: INFO/ForkPoolWorker-7] Task save_user_action[882a4253-15c0-44e6-96cd-640ca5b7526f] succeeded in 0.05143858199880924s: True
[2022-03-31 10:48:34,523: INFO/MainProcess] Received task: save_user_action[b564ff5b-cfe7-4910-b2b8-3d1c843fdde3]  
[2022-03-31 10:48:34,581: INFO/ForkPoolWorker-7] Task save_user_action[b564ff5b-cfe7-4910-b2b8-3d1c843fdde3] succeeded in 0.056460010004229844s: True
```

Usually there are also logs when you click on an encoding in the admin UI. However, no logs are shown von VP9 encodings:
<img width="833" alt="image" src="https://user-images.githubusercontent.com/9428899/161025175-561862a3-b903-4764-8728-6ad86a8cd8eb.png">

**Comment by mgogoulos** [comment]
Hi, thanks for opening this. I don't have the capacity to troubleshoot it now but if you can provide a file where it fails, it will help to reproduce it locally - because this does not seem like a generic thing (I've transcoded to vp9 without issues!)

**Comment by DecaTec** [comment]
I've already a file on the demo instance a while ago: https://demo.mediacms.io/view?m=Mxn5RCIL8
With this file (download original) and uploading to my instance, I can reproduce the problem.

**Comment by mgogoulos** [comment]
thanks, this will help debug the issue. This is the most helpful log (celery.log) from the ones you posted

```
  File "/home/mediacms.io/mediacms/files/tasks.py", line 352, in encode_media
    ret = media_file_info(tf)
  File "/home/mediacms.io/mediacms/files/helpers.py", line 446, in media_file_info
    stream_size = sum([int(line) for line in stdout.split("\n") if line != ""])
  File "/home/mediacms.io/mediacms/files/helpers.py", line 446, in <listcomp>
    stream_size = sum([int(line) for line in stdout.split("\n") if line != ""])
ValueError: invalid literal for int() with base 10: '311|'
```

**Comment by DecaTec** [comment]
Yes, that's the problem here.
Set up another instance on a virtual machine and also there I can reproduce the exact same problem.

My second logs are a bit misleading, I was too quick while copying (the encoding task wasn't run yet).

**Comment by DecaTec** [comment]
Some more information:

This is the ffprobe command issued: `ffprobe -loglevel error -select_streams a -show_entries packet=size -of compact=p=0:nk=1 /tmp/tmp9sp34h11/tmp3ssrdpei.webm`

This produces following output: 
```
3
3
3
3
3
469
...
225
266
229
232
397|
```

Have a look at the last line, seems ffprobe adds the pipe at the last line.

Temporary workaround: Change this line
```
stream_size = sum([int(line) for line in stdout.split("\n") if line != ""])
```
into this one:
```
stream_size = sum([int(line.replace("|", "")) for line in stdout.split("\n") if line != ""])
```
After restarting all services, the situation is as follows:
* The encoding doesn't fail (also no encoding related errors in the logs).
* In the admin UI unter 'encodings', the encodings are shown as 'Success' and a log output of the encoding process is also displayed.
* **However, the video has still the status "Media encoding is pending"**
* This is probably related to the status of the video unter 'Medias' in the admin UI, here it still says 'pending'

My question now is how the encoding status of a video (the original video) gets determined in the UI of MediaCMS.

**Comment by DecaTec** [comment]
Did you already find the time to have a look at the PR?

**Comment by GmodCentral** [comment]
I'm having a similar issue. 
All vp9 videos have a fail status and celery log shows this error.

```
 ERROR/ForkPoolWorker-1] Task encode_media[3475b75e-af02-4635-a72f-0145246031b1] raised unexpected: ValueError("invalid literal for int()>
Traceback (most recent call last):
  File "/home/mediacms.io/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/mediacms.io/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/mediacms.io/mediacms/files/tasks.py", line 352, in encode_media
    ret = media_file_info(tf)
  File "/home/mediacms.io/mediacms/files/helpers.py", line 446, in media_file_info
    stdout = run_command(cmd).get("out")
  File "/home/mediacms.io/mediacms/files/helpers.py", line 446, in <listcomp>
    stdout = run_command(cmd).get("out")
ValueError: invalid literal for int() with base 10: '339|'
```

**Comment by DecaTec** [comment]
@GmodCentral Yes, seems to be the same problem here.
You could try to implement the changes mentioned in https://github.com/mediacms-io/mediacms/issues/435#issuecomment-1085722122 (see PR https://github.com/mediacms-io/mediacms/pull/438)
