### ISSUE TITLE
issue with smtp settings

### ISSUE THREAD

**Issue by KvizadSaderah** [mediacms-io/mediacms#473]
**Describe the issue**
Trying to make contact form work.
Setup SMTP as described in documentation, but still got error
not docket installation, 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

**To Reproduce**
Steps to reproduce the issue:
1. `source  /home/mediacms.io/bin/activate`
2. `python manage.py shell`
3. See error

used gmail

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/config.py", line 563, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.8/logging/config.py", line 744, in configure_handler
    result = factory(**kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1147, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.8/logging/__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/home/mediacms.io/mediacms/logs/debug.log'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mediacms.io/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/mediacms.io/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/mediacms.io/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/mediacms.io/lib/python3.8/site-packages/django/utils/log.py", line 75, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python3.8/logging/config.py", line 808, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.8/logging/config.py", line 570, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'file'
```

**Comment by mgogoulos** [comment]
How was the system installed? is it docker setup or single server? I think there are multiple errors here

To start

```
PermissionError: [Errno 13] Permission denied: '/home/mediacms.io/mediacms/logs/debug.log'
```

Can you give permission to that file, as the rest of the logs/ folder? 

Is the rest of the system working? I'd be surprised if it is, with this error here. 

Then, I'm afraid that you can not use gmail credentials anymore for sending email on an application as this. Gmail has made that  change very recently, at the end of May  - https://support.google.com/accounts/answer/6010255?hl=en

I have seen multiple portals having problems with emails ever since that were not resolved...

**Comment by KvizadSaderah** [comment]
Sorry it was single server installation. 
Everything else working fine. 

would change permission a bit later and would write about result. 

IMHO it’s because of goolge new policies

**Comment by Mozitux** [comment]
I had the same issue that I was able to correct by setting the port to 587 and disabling TLS encryption (depending on your dn provider, emails will still be encrypted).

**Comment by mgogoulos** [comment]
Thanks for the comment @Mozitux , I've switched from Gmail to https://app.eu.sparkpost.com and it has been working correctly after I've setup the dns entries on the DNS provider. Requires some work but it works!
